
package br.cella.wsclient.venda;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaWs", targetNamespace = "http://webservices.cella/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaWs {


    /**
     * 
     * @param lista
     * @param valor
     * @param id
     * @param descricao
     * @return
     *     returns br.cella.wsclient.venda.Venda
     */
    @WebMethod
    @WebResult(name = "resultadoVenda", targetNamespace = "")
    @RequestWrapper(localName = "operacaoVenda", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.venda.OperacaoVenda")
    @ResponseWrapper(localName = "operacaoVendaResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.venda.OperacaoVendaResponse")
    public Venda operacaoVenda(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "descricao", targetNamespace = "")
        String descricao,
        @WebParam(name = "valor", targetNamespace = "")
        BigDecimal valor,
        @WebParam(name = "lista", targetNamespace = "")
        List<Object> lista);

}
