
package br.cella.wsclient.produto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProdutoWsService", targetNamespace = "http://webservices.cella/", wsdlLocation = "http://localhost:8085/lab148352/ProdutoWs?wsdl")
public class ProdutoWsService
    extends Service
{

    private final static URL PRODUTOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUTOWSSERVICE_EXCEPTION;
    private final static QName PRODUTOWSSERVICE_QNAME = new QName("http://webservices.cella/", "ProdutoWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/lab148352/ProdutoWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUTOWSSERVICE_WSDL_LOCATION = url;
        PRODUTOWSSERVICE_EXCEPTION = e;
    }

    public ProdutoWsService() {
        super(__getWsdlLocation(), PRODUTOWSSERVICE_QNAME);
    }

    public ProdutoWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUTOWSSERVICE_QNAME, features);
    }

    public ProdutoWsService(URL wsdlLocation) {
        super(wsdlLocation, PRODUTOWSSERVICE_QNAME);
    }

    public ProdutoWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUTOWSSERVICE_QNAME, features);
    }

    public ProdutoWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProdutoWs
     */
    @WebEndpoint(name = "ProdutoWsPort")
    public ProdutoWs getProdutoWsPort() {
        return super.getPort(new QName("http://webservices.cella/", "ProdutoWsPort"), ProdutoWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProdutoWs
     */
    @WebEndpoint(name = "ProdutoWsPort")
    public ProdutoWs getProdutoWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.cella/", "ProdutoWsPort"), ProdutoWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUTOWSSERVICE_EXCEPTION!= null) {
            throw PRODUTOWSSERVICE_EXCEPTION;
        }
        return PRODUTOWSSERVICE_WSDL_LOCATION;
    }

}
