
package br.cella.wsclient.produto;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoWs", targetNamespace = "http://webservices.cella/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoWs {


    /**
     * 
     * @param preco
     * @param codBarras
     * @param descricao
     */
    @WebMethod
    @RequestWrapper(localName = "salvar", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.Salvar")
    @ResponseWrapper(localName = "salvarResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.SalvarResponse")
    public void salvar(
        @WebParam(name = "codBarras", targetNamespace = "")
        String codBarras,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco,
        @WebParam(name = "descricao", targetNamespace = "")
        String descricao);

    /**
     * 
     * @param preco
     * @param id
     * @param codBarras
     * @param descricao
     */
    @WebMethod
    @RequestWrapper(localName = "atualziar", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.Atualziar")
    @ResponseWrapper(localName = "atualziarResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.AtualziarResponse")
    public void atualziar(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "codBarras", targetNamespace = "")
        String codBarras,
        @WebParam(name = "preco", targetNamespace = "")
        BigDecimal preco,
        @WebParam(name = "descricao", targetNamespace = "")
        String descricao);

    /**
     * 
     * @param id
     * @return
     *     returns br.cella.wsclient.produto.Produto
     */
    @WebMethod
    @WebResult(name = "resultadobuscar", targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.BuscarResponse")
    public Produto buscar(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletar", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.Deletar")
    @ResponseWrapper(localName = "deletarResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.produto.DeletarResponse")
    public void deletar(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
