
package br.cella.wsclient.entrega;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaWs", targetNamespace = "http://webservices.cella/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaWs {


    /**
     * 
     * @param enredeco
     * @return
     *     returns br.cella.wsclient.entrega.Entrega
     */
    @WebMethod
    @WebResult(name = "resultadoEntrega", targetNamespace = "")
    @RequestWrapper(localName = "operacaoEntrega", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.entrega.OperacaoEntrega")
    @ResponseWrapper(localName = "operacaoEntregaResponse", targetNamespace = "http://webservices.cella/", className = "br.cella.wsclient.entrega.OperacaoEntregaResponse")
    public Entrega operacaoEntrega(
        @WebParam(name = "enredeco", targetNamespace = "")
        String enredeco);

}
