
package br.cella.wsclient.entrega;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntregaWsService", targetNamespace = "http://webservices.cella/", wsdlLocation = "http://localhost:8085/lab148352/EntregaWs?wsdl")
public class EntregaWsService
    extends Service
{

    private final static URL ENTREGAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTREGAWSSERVICE_EXCEPTION;
    private final static QName ENTREGAWSSERVICE_QNAME = new QName("http://webservices.cella/", "EntregaWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/lab148352/EntregaWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTREGAWSSERVICE_WSDL_LOCATION = url;
        ENTREGAWSSERVICE_EXCEPTION = e;
    }

    public EntregaWsService() {
        super(__getWsdlLocation(), ENTREGAWSSERVICE_QNAME);
    }

    public EntregaWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTREGAWSSERVICE_QNAME, features);
    }

    public EntregaWsService(URL wsdlLocation) {
        super(wsdlLocation, ENTREGAWSSERVICE_QNAME);
    }

    public EntregaWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTREGAWSSERVICE_QNAME, features);
    }

    public EntregaWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntregaWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntregaWs
     */
    @WebEndpoint(name = "EntregaWsPort")
    public EntregaWs getEntregaWsPort() {
        return super.getPort(new QName("http://webservices.cella/", "EntregaWsPort"), EntregaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntregaWs
     */
    @WebEndpoint(name = "EntregaWsPort")
    public EntregaWs getEntregaWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.cella/", "EntregaWsPort"), EntregaWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTREGAWSSERVICE_EXCEPTION!= null) {
            throw ENTREGAWSSERVICE_EXCEPTION;
        }
        return ENTREGAWSSERVICE_WSDL_LOCATION;
    }

}
